### ISSUE TITLE
Add section "Contact Us" in the customer page

### ISSUE THREAD

**Issue by joakim-olesen** [Etimo/homepage#101]
Add a section after all current sections on https://etimo.se/kunder-och-expertis

The left menu link text should be "Kontakt".

The section should be like this:
![image](https://user-images.githubusercontent.com/8019171/111607086-3661d900-87d8-11eb-80fc-acc343af052f.png)

It is very similar to the last section on https://etimo.se/karriar/ so parts can probably be copied from there.

**Comment by indrif** [comment]
In the career section we use the phrase "Skicka ett mail till oss" while here we use the phrase "Skicka ett mail till Johan". Should we be consistent and use the same phrase instead?

**Comment by joakim-olesen** [comment]
I actually asked the same question "internally" and the response I got was that it should not be the same.
