### ISSUE TITLE
Start page photos

### ISSUE THREAD

**Issue by joakim-olesen** [Etimo/homepage#144]
Some photos in section "Några av oss" and section "Kul på jobbet" on the start page should be replaced with other photos. 

The photos need to be taken (or found if using existing ones) and perhaps modified to fit into the page in a good way and finally the website needs to be updated with the new photos.

Try to come up with some ideas together with Jeanette and keep Joakim in the loop.

**Comment by hejsaga** [comment]
I've updated the photos in section "kul på jobbet" and will create a new issue for section "några av oss" since we're taking another creative direction there and want to push these changes to production now.
