### ISSUE TITLE
Use a different build image due to deprecation

### ISSUE THREAD

**Issue by joakim-olesen** [Etimo/homepage#167]
E-mail from netlify:

> Deprecation notice: Netlify builds using the Xenial build image will fail after November 15, 2022
> 
> The Netlify build system maintains multiple [build images](https://communications.netlify.com/e3t/Ctc/I6+113/cVvsj04/VWZKk452SlVvV19HG44wp0-DW2dmkKk4PDJWWN6Q02sJ3q3phV1-WJV7CgGNWW5qJh1P3QrYTjW9lGJ2p5rfVTmW2MHMsG8nPNQhN1V6ltwzbTZnN7gNXPxNBc5GW1vmxTv29rqfZVPn2QR8d2XQ1W6Gmqx5136tBQN68KzRlST90VN3cb8_Xy60ByW8ZbTzL1wf9gKVK11Hm5ygtF-TtFt01gcjL7W17qvS28JSh4QW3Hc1pv2ZLyMPW8TfgNr23vXn0W7kYZj_8nVTCtVHQZyp8wKBBlW7SyfVy4BpL-QW8BwJVh8-VtPcW2f3C708KwPHsW58YjvH7pQVHmW2bCrG59679TRW8JGhWk6zkc0HW50wyl97Xt42HW7t-sjy3wT_F4W5CFskG6yzlgBW6KRNSg3hvf1f3dqM1), which set the environment in which your sites build. One or more of your sites is using the “Xenial” image, built on Ubuntu 16.04 (“Xenial Xerus”). Ubuntu Xenial finished its Long Term Support period in 2021 and is [no longer supported by Canonical](https://communications.netlify.com/e3t/Ctc/I6+113/cVvsj04/VWZKk452SlVvV19HG44wp0-DW2dmkKk4PDJWWN6Q02rQ3q3npV1-WJV7CgWDPW5YF1hM3bPHX2Vt_rH95dRgGqW6qnNt93rwt85W9jzd7V4ZcjktW31py8d8nnLvjN2vf1rmlmg3NW48sfZm1r_q3jMds8ylpVvrxW4MZ8Yj2nMc-_W5qzQhp8RRnlVW3tt1Lj4D9ZSbW4_ytfJ3dJ50cW4s4Dh_39bg0GW7VtrRN3S4bGgW3qQKnP2t6qLpW5Pvkjg8FFl9JW7sX9lW7qcP1cW5Ns8gS2C2z2CW2wkkJ93rWSxLW9fcZ9G3-GLlhW2pndBw97rqSSW4B4YXN372_zX3mYY1), a 3rd party company that provides official ubuntu support. This means no new bug fixes and security updates, nor new versions of included software.
> 
> On November 15, 2022, we will end all support for the Netlify Xenial image. We have identified the following impacted sites belonging to your team Etimo:
> 
> [etimo-homepage](https://communications.netlify.com/e3t/Ctc/I6+113/cVvsj04/VWZKk452SlVvV19HG44wp0-DW2dmkKk4PDJWWN6Q02sJ3pds1V1-WJV7CgFKNW1g5V9F7-3mZgW6nRwDn2nTN5PN3VT74bbl4BkW6_R9cT60k1fyW5nTRDM2-YwYRW8H7Rv7764hq6N2fM9n2mRCRFW6kdccb7N_8JZW6hlwLy2BnzKYW5QQZzp3xdN4KW2h2NCH3-K4v2W25pSSm6THMJbW527yyR40qHS0VvBmpZ29YpxbW6CSB2x5ZVr1CW6rG3f98wtd7yW5g9bCP4G23yVW6vNTj733wTpCVGvrnn1j4GHNW8dNp232101JlW7rf-3t81HQf9W3P9Dg63F-Gm4W1J3y5W28GgybN7LLQ1sqB4pqW6cR80D3Vt2R2W5lfbYm14HWs5W1jPfjn3_Vy6NW7v0xSg8qxLH1346v1)
> 
> Select a site name above to access specific site settings in the Netlify UI where you can change the site’s build image.
> 
> For more information about changes between images, a timeline, how to run a test build, and how to troubleshoot issues with upgrading, please visit the [Xenial build image migration guide](https://communications.netlify.com/e3t/Ctc/I6+113/cVvsj04/VWZKk452SlVvV19HG44wp0-DW2dmkKk4PDJWWN6Q02qX5nCTJV3Zsc37CgMQLW2QxqDN3Qry2sN3vN1YvPtjxTN12Q-YkvWsQ8W27lwsX2CdQyxW7wC_nf3fkV3KW6Wgp4f3V0hSJW7w-g9b5NTC5CW4Scndw5tGNw4W65V6-71ZDJyXW54__vw1QJKFmW3sGvnF8zKJrxW500V5w2DcK-_VHXDdX8Xz5V3W68H8rk7kYkhZN7XptZDKdPKGW1Fhrkf2gytQHW67_ZM47gHFZ3Vkt0D62SZdB0W69tXVx1Nj5nSW8tVfXp2YQgRFW4C5Jb54rgT9PW9k3xh67DvknjW2pmJ1_60bq-3W47HYNV8d-cdhW4HnhJ18g6HQQW8M4hkC3FTnB6W8fSlrt7Sqvx9W1qqdjV2Wp4PbW4nqKJY5swFCJVQ4FC35MJstMW6r-Q1p3-l8VjW8-3J7B6t90cs3g1l1) in the Netlify Support Forums.
> 
> As always, we’re here to help! If you have any questions, feel free to reply to this email directly.

**Comment by hejsaga** [comment]
Closed this spring.
