### ISSUE TITLE
Font, spacing, positioning and margins

### ISSUE THREAD

**Issue by joakim-olesen** [Etimo/homepage#17]
1. Improve fonts. Something like this might be good for the "ordinary" text:
    font-family: "Segoe UI";
    font-size: 14px;
    line-height: 2.3;
    font-weight: 100;
    letter-spacing: 0.05em;
2. Fix margins in general. For example, the small text "ATT JOBBA PÅ ETIMO" is too close to the text below it.
3. List items that span two lines should be idented on the second line, so the text isn't just below the bullet symbol. Hence it should be like the bullets in this github comment.
4. "Hur är det att jobba på Etimo?" should have an additional line break between "det" and "att".
5. Logos in "Kunder" should have larger margin

**Comment by affeproffs** [comment]
1. There seems to be a licensing issue (owned by microsoft) with using Segoe UI.
Maybe open sans (https://fonts.google.com/specimen/Open+Sans) instead?
