### ISSUE TITLE
Investigate website traffic tools for etimo.se 

### ISSUE THREAD

**Issue by malinlindbom** [Etimo/homepage#192]
**Description** 
In order for us to make informed decisions about etimo.se, it's important to get as much insights and knowledge about our visitors. There are several tools on the market that can be used for this purpose, but whichever tool we decide on it needs to be inline with current legislation around saving data, i.e. gdpr.   

Since we have used google analytics in the past, it can be a good place to start.  

**Included in the ticket**
Investigate if latest version of google analytics is fit for purpose, i.e. saves data inline with gdpr. If yes, 

**Goal with the ticket** 
- Be able to say yes or no to if we can use google analytics latest version to track website traffic
- Understand if they comply with gdpr

**Comment by klaradj** [comment]
GA4 comply with GDPR as long as we use cookie consent and anonymize = true.
