### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by joakim-olesen** [Etimo/homepage#49]
We can use a tool like lighthouse to check performance. It was done on 2020-07-05 for the start page, see the attached lighthouse report (but run it again when working on this ticket).

The website shouldn't be perfect, but some parts can likely easily be improved. For instance, faster loading of images on mobile devices.

[lighthouse etimose.pdf](https://github.com/Etimo/homepage/files/4875204/lighthouse.etimose.pdf)

Additional information:
![image](https://user-images.githubusercontent.com/8019171/86565718-ac832000-bf68-11ea-8856-3ac9467b83ef.png)

**Comment by affeproffs** [comment]
![etimoping](https://user-images.githubusercontent.com/52673311/86953137-4529c380-c154-11ea-8165-0fd8bc83523e.png)

The hosting seems to probably be the biggest reason as to why images load slowly on mobile.

This can be seen by the image of pings above, as well as https://etimo-homepage.netlify.app/ not having the same problem
as the main page, even though they both share the exact same code base.

- RTT of etimo.se: **156ms**
- RTT of etimo-homepage.netlify.app: **35ms**

**Comment by indrif** [comment]
Can we upload the images to a cdn instead of storing them locally if it would still be a problem later on?

**Comment by joakim-olesen** [comment]
We think performance is good enough for now so I close this ticket
