### ISSUE TITLE
Add google analytics tracking

### ISSUE THREAD

**Issue by joakim-olesen** [Etimo/homepage#70]
Tracking id: UA-47276360-1

Perhaps there is some built in way to do this with gatsby. However, a google analytics example tracking code (copied from google analytics) is below. It's Global Site Tag (gtag.js) which seems to be recommended now (don't know how it differs from other ways of doing it). 
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47276360-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-47276360-1');
</script>
```

**Comment by ljukas** [comment]
Solved. Change pushed to master.
