### ISSUE TITLE
Backup old website

### ISSUE THREAD

**Issue by joakim-olesen** [Etimo/homepage#98]
Backup old website and store it on our google drive. Also, make a restore (on your own computer or in a virtual machine or something like that) just to verify that the backup is okay.

When the backup is made, Joakim can delete the old website so we no longer pay for it.

**Comment by joakim-olesen** [comment]
Backup is now available on our google drive. Search for site-archive-vnext and you shall find.

**Comment by indrif** [comment]
Created a docker compose project that can run the site. Will create a private repo for it.

**Comment by indrif** [comment]
Uploaded to private repo.
